import type { AppLanguage } from "../../shared/settings/appSettings.ts";

const STORAGE_SETTINGS_COPY = {
  "zh-CN": {
    storageLocalTitle: "本地存储",
    storageLocalHint: "管理活动数据库与 WebView 持久数据的位置。迁移会在重启时执行，旧目录不会自动删除。",
    storageDataTitle: "活动数据",
    storageDataHint: "包含 Patina 数据库和本地备份。",
    storageWebviewTitle: "WebView 数据",
    storageWebviewHint: "包含界面持久状态和可重新生成的 WebKit 缓存。",
    storageDefault: "默认",
    storageCustom: "自定义",
    storageOpen: "打开",
    storageMove: "移动",
    storageRestoreDefault: "恢复默认",
    storageCacheTitle: "WebKit 缓存",
    storageCacheClearOnRestart: "重启时清理",
    storagePendingTitle: "等待重启迁移",
    storagePendingCancel: "取消迁移",
    storageRetainedTitle: "保留的旧目录",
    storageLoading: "正在读取存储状态...",
    storageRetry: "重试",
    storageActionLabel: (action: string, target: string) => `${action}${/^[A-Za-z]/.test(target) ? " " : ""}${target}`,
    storageCacheHint: "仅清理可重新生成的 WebKitCache，不会删除整个 WebView 数据目录。",
    storageRestartPending: "重启并迁移",
    storageLastErrorTitle: "上次存储维护失败",
    storageMoveConfirmTitle: "预约存储迁移",
    storageRestoreDefaultConfirmTitle: "恢复默认存储位置",
    storageMoveConfirmDetail: (source: string, target: string, size: string) => `来源：${source}\n目标：${target}\n预计复制：${size}\n\n迁移会在重启时执行，旧目录将保留。`,
    storageScheduleAction: "预约迁移",
    storageRestartTitle: "现在重启 Patina？",
    storageRestartDetail: "迁移已预约。重启后会先验证并迁移数据，再启动追踪。",
    storageRestartNow: "立即重启",
    storageRestartLater: "稍后",
    storageScheduled: "存储迁移已预约。",
    storagePendingCancelled: "已取消等待中的存储迁移。",
    storageLoadFailed: "无法读取本地存储状态。",
    storageActionFailed: "存储操作失败，请检查目录和可用空间。",
  },
  "en-US": {
    storageLocalTitle: "Local storage",
    storageLocalHint: "Manage the activity database and persistent WebView data. Moves run after restart and old directories are retained.",
    storageDataTitle: "Activity data",
    storageDataHint: "Contains the Patina database and local backups.",
    storageWebviewTitle: "WebView data",
    storageWebviewHint: "Contains persistent interface state and regenerable WebKit cache.",
    storageDefault: "Default",
    storageCustom: "Custom",
    storageOpen: "Open",
    storageMove: "Move",
    storageRestoreDefault: "Restore default",
    storageCacheTitle: "WebKit cache",
    storageCacheClearOnRestart: "Clear on restart",
    storagePendingTitle: "Migration pending restart",
    storagePendingCancel: "Cancel migration",
    storageRetainedTitle: "Retained previous directories",
    storageLoading: "Reading storage status...",
    storageRetry: "Retry",
    storageActionLabel: (action: string, target: string) => `${action} ${target}`,
    storageCacheHint: "Only regenerable WebKitCache is cleared; the WebView data directory is retained.",
    storageRestartPending: "Restart and migrate",
    storageLastErrorTitle: "Last storage maintenance failed",
    storageMoveConfirmTitle: "Schedule storage migration",
    storageRestoreDefaultConfirmTitle: "Restore default storage location",
    storageMoveConfirmDetail: (source: string, target: string, size: string) => `Source: ${source}\nTarget: ${target}\nEstimated copy: ${size}\n\nThe migration runs after restart and the old directory is retained.`,
    storageScheduleAction: "Schedule migration",
    storageRestartTitle: "Restart Patina now?",
    storageRestartDetail: "The migration is scheduled. Patina will validate and move data before tracking starts.",
    storageRestartNow: "Restart now",
    storageRestartLater: "Later",
    storageScheduled: "Storage migration scheduled.",
    storagePendingCancelled: "Pending storage migration cancelled.",
    storageLoadFailed: "Could not read local storage status.",
    storageActionFailed: "Storage action failed. Check the directory and available space.",
  },
} as const;

export function getStorageSettingsCopy(language: AppLanguage) {
  return STORAGE_SETTINGS_COPY[language];
}

export type StorageSettingsCopy = ReturnType<typeof getStorageSettingsCopy>;
