pub(crate) mod appimage_runtime;
#[cfg(feature = "desktop")]
pub(crate) mod appimage_update;
pub mod audio;
pub mod foreground;
pub mod icon;
pub mod input;
pub mod media;
pub mod notifications;
pub mod power;
pub mod resource;
pub mod systemd_user_service;
pub(crate) mod patinad_service_unit;
pub(crate) mod standalone_runtime;
pub(crate) mod executable_identity;
#[cfg(feature = "desktop")]
pub mod widget_window;
#[cfg(feature = "desktop")]
pub mod window_activation;

pub(super) mod session;
